export interface ProductInfo {
  id: string;
  shortName: string;
  title: string;
  price: string;
  originalPrice: string;
  discount: string;
  saving: string;
  rating: string;
  reviews: number;
  sold: string;
  shipping: string;
  seller: string;
  colors: string[];
  sizes: string[];
}

export interface UgcNode {
  id: string;
  label: string;
  category: 'Producto' | 'Color' | 'Detalle' | 'Prueba' | 'Conversión' | 'Oportunidad';
  image: string;
  imageAlt: string;
  video?: string;
  extractedFact: string;
  angle: string;
  hook: string;
  format: string;
  shots: string[];
  cta: string;
  evidence: string;
}

export const PRODUCT: ProductInfo = {
  id: '1732992473481512755',
  shortName: 'Chaqueta de ante sintético',
  title: 'Chaqueta para hombre con cuello, cierre de cremallera y acabado de piel sintética',
  price: '$408.15 MXN',
  originalPrice: '$867.61',
  discount: '53%',
  saving: 'Ahorro de $459.46',
  rating: '4.9',
  reviews: 280,
  sold: '3,305',
  shipping: 'Envío gratis',
  seller: 'Value Chic Clothes',
  colors: ['Caramelo', 'Gris claro', 'Negro', 'Verde oliva', 'Gris oscuro'],
  sizes: ['S', 'M', 'L', 'XL', 'XXL'],
};

export const CONTENT_NODES: UgcNode[] = [
  {
    id: 'hero-value',
    label: 'Vista frontal',
    category: 'Producto',
    image: '/product/01_gallery.jpg',
    imageAlt: 'Chaqueta color caramelo vista de frente',
    extractedFact: 'Precio extraído: $408.15 MXN, antes $867.61; descuento reportado de 53%.',
    angle: 'La chaqueta que cambia un look sin elevar el presupuesto',
    hook: 'Parece una chaqueta de más de $800, pero hoy cuesta menos de la mitad.',
    format: 'Reel vertical 9:16 · 15–20 s',
    shots: ['Entrada con look básico', 'Reveal de la chaqueta', 'Detalle del precio en pantalla', 'Plano completo en movimiento'],
    cta: 'Descubre el color que mejor encaja con tu estilo.',
    evidence: 'normalized.json · price_info',
  },
  {
    id: 'caramel',
    label: 'Caramelo',
    category: 'Color',
    image: '/product/10_variant.jpg',
    imageAlt: 'Chaqueta variante color caramelo',
    video: '/product/jacket_colors_loop_20s.mp4',
    extractedFact: 'Caramelo es una de las 5 variantes de color y suma 163 unidades de stock capturado.',
    angle: 'Un neutro cálido para rotar tres outfits',
    hook: 'Si todo tu clóset es negro, este es el color que lo despierta.',
    format: 'Reel de estilismo 9:16 · 20 s',
    shots: ['Look monocromático negro', 'Cambio a camiseta blanca', 'Combinación con denim', 'Loop de los cinco colores'],
    cta: 'Guarda el look y compara las cinco variantes.',
    evidence: 'normalized.json · variants',
  },
  {
    id: 'light-gray',
    label: 'Gris claro',
    category: 'Color',
    image: '/product/11_variant.jpg',
    imageAlt: 'Chaqueta variante color gris claro',
    extractedFact: 'Gris claro aparece como variante disponible en tallas S, L y XL dentro de la captura.',
    angle: 'El tono limpio para un armario minimalista',
    hook: 'El gris que hace que un outfit sencillo se vea intencional.',
    format: 'Get ready with me · 18 s',
    shots: ['Prenda sobre fondo neutro', 'Camiseta y pantalón base', 'Chaqueta como última capa', 'Plano espejo final'],
    cta: 'Elige tu talla antes de que cambie la disponibilidad.',
    evidence: 'variants.csv · color gris claro',
  },
  {
    id: 'black',
    label: 'Negro',
    category: 'Color',
    image: '/product/12_variant.jpg',
    imageAlt: 'Chaqueta variante color negro',
    extractedFact: 'La variante negra registra stock en S, M, L, XL y XXL; 77 unidades sumadas.',
    angle: 'La opción segura que funciona de día y de noche',
    hook: 'Una sola chaqueta, dos códigos de vestuario.',
    format: 'Transición día/noche · 15 s',
    shots: ['Look casual de día', 'Tap a cámara', 'Cambio de accesorios', 'Look nocturno completo'],
    cta: 'Comenta DÍA o NOCHE para elegir el siguiente styling.',
    evidence: 'variants.csv · Negro',
  },
  {
    id: 'olive',
    label: 'Verde oliva',
    category: 'Color',
    image: '/product/13_variant.jpg',
    imageAlt: 'Chaqueta variante color verde oliva',
    extractedFact: 'Verde oliva registra las cinco tallas y 35 unidades de stock capturado.',
    angle: 'El color menos obvio para destacar sin exagerar',
    hook: 'No es negro, no es café: por eso eleva el outfit.',
    format: 'POV de elección · 12–15 s',
    shots: ['Tres chaquetas en rack', 'Mano elige verde oliva', 'Macro del tono', 'Outfit final caminando'],
    cta: '¿Oliva o caramelo? Deja tu elección.',
    evidence: 'variants.csv · Verde oliva',
  },
  {
    id: 'dark-gray',
    label: 'Gris oscuro',
    category: 'Color',
    image: '/product/14_variant.jpg',
    imageAlt: 'Chaqueta variante color gris oscuro',
    extractedFact: 'Gris oscuro tiene 14 unidades capturadas y disponibilidad registrada en S y M.',
    angle: 'Una alternativa suave al negro total',
    hook: 'El truco para vestir oscuro sin repetir el mismo negro.',
    format: 'Reel comparativo · 15 s',
    shots: ['Negro y gris lado a lado', 'Cambio rápido de prenda', 'Close-up bajo luz natural', 'Selección final'],
    cta: 'Revisa la talla disponible antes de elegir color.',
    evidence: 'variants.csv · Gris oscuro',
  },
  {
    id: 'back-shape',
    label: 'Vista trasera',
    category: 'Producto',
    image: '/product/06_gallery.jpg',
    imageAlt: 'Chaqueta color caramelo vista por detrás',
    extractedFact: 'La galería incluye una vista trasera completa con canesú y costura horizontal visibles.',
    angle: 'Cómo se ve realmente desde todos los ángulos',
    hook: 'El frente vende la idea; la espalda confirma el fit.',
    format: 'Prueba 360° · 12 s',
    shots: ['Frente estático', 'Giro lateral', 'Vista trasera completa', 'Regreso a cámara'],
    cta: 'Guarda esta referencia para comparar el ajuste.',
    evidence: 'images/06_gallery.jpg',
  },
  {
    id: 'size-guide',
    label: 'Guía de tallas',
    category: 'Conversión',
    image: '/product/15_description.jpg',
    imageAlt: 'Tabla de tallas extraída del producto',
    extractedFact: 'La tabla cubre S–XXL; pecho de 112 a 130 cm y largo de 69 a 77 cm.',
    angle: 'Cómo elegir talla sin adivinar',
    hook: 'Antes de pedirla, mide esto en una chaqueta que ya te quede bien.',
    format: 'Tutorial a cámara · 25 s',
    shots: ['Extender una chaqueta propia', 'Medir pecho', 'Medir largo', 'Cruzar medidas con la tabla'],
    cta: 'Haz captura de la tabla y compara tus medidas.',
    evidence: 'sizechart.json',
  },
  {
    id: 'collar',
    label: 'Cuello clásico',
    category: 'Detalle',
    image: '/product/16_description.jpg',
    imageAlt: 'Detalle frontal y cuello de la chaqueta caramelo',
    extractedFact: 'La descripción reporta cuello clásico y cierre frontal de cremallera.',
    angle: 'El detalle que permite vestirla casual o más pulida',
    hook: 'Un cuello cambia por completo la lectura de una chaqueta.',
    format: 'Detalle + styling · 15 s',
    shots: ['Cuello abierto', 'Cuello acomodado', 'Look con camiseta', 'Look con camisa'],
    cta: 'Prueba ambos estilos y elige tu favorito.',
    evidence: 'product_extract.json · description',
  },
  {
    id: 'zipper',
    label: 'Cremallera',
    category: 'Detalle',
    image: '/product/18_description.jpg',
    imageAlt: 'Primer plano de la cremallera y el tejido',
    extractedFact: 'La galería de descripción incluye un macro del cierre metálico sobre el tejido sintético.',
    angle: 'Textura que se percibe premium en cámara',
    hook: 'No parece sintético hasta que miras el precio.',
    format: 'ASMR de producto · 10–12 s',
    shots: ['Macro de textura', 'Abrir cremallera', 'Cerrar cremallera', 'Paneo sobre la costura'],
    cta: 'Activa el sonido y mira los detalles de cerca.',
    evidence: 'images/18_description.jpg',
  },
  {
    id: 'hem',
    label: 'Dobladillo',
    category: 'Detalle',
    image: '/product/19_description.jpg',
    imageAlt: 'Detalle del dobladillo y costura de la chaqueta',
    extractedFact: 'La extracción visual documenta el remate inferior y sus líneas de costura.',
    angle: 'Tres señales visuales para evaluar acabados online',
    hook: 'Antes de comprar una chaqueta por internet, revisa estas costuras.',
    format: 'Checklist visual · 18 s',
    shots: ['Remate inferior', 'Costura en diagonal', 'Unión de paneles', 'Vista completa'],
    cta: 'Guarda el checklist para tu próxima compra.',
    evidence: 'images/19_description.jpg',
  },
  {
    id: 'cuff',
    label: 'Puño con botón',
    category: 'Detalle',
    image: '/product/20_description.jpg',
    imageAlt: 'Detalle del puño con botón',
    extractedFact: 'La imagen de detalle muestra puño terminado con botón metálico.',
    angle: 'Un detalle pequeño que cambia el fit de la manga',
    hook: 'Así haces que la manga se vea más estructurada en segundos.',
    format: 'Microtutorial · 12 s',
    shots: ['Puño abierto', 'Cerrar el botón', 'Doblar ligeramente', 'Brazo en movimiento'],
    cta: 'Guarda el ajuste para probarlo con tu chaqueta.',
    evidence: 'images/20_description.jpg',
  },
  {
    id: 'seams',
    label: 'Costuras',
    category: 'Detalle',
    image: '/product/21_description.jpg',
    imageAlt: 'Macro de costuras reforzadas sobre el material',
    extractedFact: 'La fotografía de detalle permite ver costuras dobles y la superficie del material.',
    angle: 'La prueba de cámara que comunica construcción',
    hook: 'El detalle que casi ninguna ficha de producto te enseña así de cerca.',
    format: 'Macro cinematográfico · 10 s',
    shots: ['Luz rasante sobre costura', 'Seguimiento de la línea', 'Presión suave del tejido', 'Corte al producto completo'],
    cta: 'Mira el resto de detalles en el mundo del producto.',
    evidence: 'images/21_description.jpg',
  },
  {
    id: 'texture',
    label: 'Textura',
    category: 'Detalle',
    image: '/product/22_description.jpg',
    imageAlt: 'Detalle del material sintético plegado',
    extractedFact: 'La descripción identifica el material como ante sintético duradero.',
    angle: 'Mostrar tacto y caída sin poder tocar el producto',
    hook: 'La mejor forma de vender textura es hacerla visible.',
    format: 'Reel sensorial · 12–15 s',
    shots: ['Deslizar mano sobre la tela', 'Pliegue lento', 'Luz lateral', 'Transición a vista completa'],
    cta: 'Explora los colores y encuentra tu acabado favorito.',
    evidence: 'product_extract.json · material',
  },
  {
    id: 'social-proof',
    label: 'Prueba social',
    category: 'Prueba',
    image: '/product/03_gallery.jpg',
    imageAlt: 'Chaqueta negra usada como fondo de métricas',
    extractedFact: 'La ficha reporta 4.9 de calificación, 280 reseñas y 3,305 vendidos.',
    angle: 'Tres cifras para abrir un video de validación',
    hook: 'Más de 3 mil ventas y una calificación de 4.9: veamos qué ofrece.',
    format: 'Review basada en ficha · 25–30 s',
    shots: ['Métricas en pantalla', 'Vista frontal', 'Tres detalles de construcción', 'Conclusión sin testimonio fingido'],
    cta: 'Consulta la ficha actual antes de tomar una decisión.',
    evidence: 'normalized.json · social_proof',
  },
  {
    id: 'shipping',
    label: 'Envío gratis',
    category: 'Conversión',
    image: '/product/08_gallery.jpg',
    imageAlt: 'Chaqueta negra vista trasera',
    extractedFact: 'La extracción registra envío gratis para la oferta capturada.',
    angle: 'Convertir el costo total en el cierre del mensaje',
    hook: 'El precio llama la atención; el envío gratis termina de explicarlo.',
    format: 'Video directo a oferta · 12 s',
    shots: ['Precio actual', 'Texto “envío gratis”', 'Producto girando', 'Pantalla final con aviso de verificar vigencia'],
    cta: 'Comprueba que la oferta siga vigente en la ficha.',
    evidence: 'normalized.json · shipping_info',
  },
  {
    id: 'availability',
    label: 'Disponibilidad',
    category: 'Conversión',
    image: '/product/05_gallery.jpg',
    imageAlt: 'Chaqueta gris oscuro vista frontal',
    extractedFact: 'La captura suma 309 unidades entre colores; la disponibilidad cambia según talla y variante.',
    angle: 'Ayudar a elegir color con información útil, no con urgencia artificial',
    hook: 'Tu color favorito puede no tener todas las tallas: revisa esto primero.',
    format: 'Guía rápida · 20 s',
    shots: ['Mapa de cinco colores', 'Stock por color', 'Tallas disponibles', 'Recordatorio de verificar la ficha'],
    cta: 'Primero talla, después color.',
    evidence: 'variants.csv · stock sumado',
  },
  {
    id: 'creator-gap',
    label: 'Vacío UGC',
    category: 'Oportunidad',
    image: '/product/09_gallery.jpg',
    imageAlt: 'Chaqueta verde oliva vista trasera',
    extractedFact: 'La captura H5 no expuso videos de creadores ni imágenes de reseñas; no se extrajeron testimonios.',
    angle: 'Construir la primera biblioteca UGC verificable del producto',
    hook: 'La ficha ya tiene datos; lo que falta es verla en uso real.',
    format: 'Serie UGC · 4 piezas',
    shots: ['Fit real frente/espejo', 'Prueba de textura', 'Tres outfits', 'Guía honesta de talla'],
    cta: 'Producir contenido original y etiquetarlo como experiencia del creador.',
    evidence: 'creator_videos.txt · review_images_urls.txt',
  },
];
